apiVersion: apps/v1
kind: Deployment

metadata:
  name: learn-git-branching
  labels:
    app: learn-git-branching

spec:
  replicas: 1

  selector:
    matchLabels:
      app: learn-git-branching

  template:
    metadata:
      labels:
        app: learn-git-branching

    spec:
      containers:
      - name: learn-git-branching
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always

        ports:
        - containerPort: 80